server:
  port: 9004

spring:
  application:
    name: provider-order       # 这是该实例注册到eureka服务端的name（这是服务名称，可以有多个相同名称但实例id不同的来做集群）

eureka:
  client:
    serviceUrl:
      # eureka服务器提供的注册地址 参考服务端配置的这个路径
      defaultZone: http://eureka:3000/eureka,http://eureka:3001/eureka,http://eureka:3002/eureka
    # 服务提供者在启动时，会之歌参数是不是正确的的，默认是true，且如果是true就会想EurekaServer发送一个Rest请求
    register-with-eureka: true
  instance:
    instance-id: order-1      # 该实例注册到eureka服务器端的唯一的实例id
    prefer-ip-address: true   # 是否显示IP地址
    # eureka客户端多长时间会发送心跳给eureka服务器，表明它仍然活着，默认情况是30s
    lease-renewal-interval-in-seconds: 10
    # eureka服务器在接收到实例最后的一次发出的心跳后，需要等待多久才可以将次实例删除，默认为90s
    # 即服务失效时间，超过30s没有向EurekaServer发送心跳的话，就认为已经宕机了
    lease-expiration-duration-in-seconds: 30